### ISSUE TITLE
Release of training code

### ISSUE THREAD

**Issue by liuyjchj1** [weihao1115/cat-sam#1]
hello，When will the training code be published?And what are the requirements for the training configuration？

**Comment by weihao1115** [comment]
Hi @liuyjchj1 

Thank you for your interest in our work!

We will release the training code upon acceptance. We used A6000 for all training tasks. However, except for the WHU dataset, a GPU with 24G memory will be enough for training 1-shot experiments. As for 16-shot and full-shot experiments, we conducted them on 4 x A6000 GPUs.

**Comment by AllenYkl** [comment]
Great work! Congrats!
Any plans for the release of training code? 
Thx a lot!

**Comment by weihao1115** [comment]
Hi @AllenYkl 
Thank you for your interest in our work!

We are currently preparing the final release of the training code and expect to complete this process within this month.
