### ISSUE TITLE
Some questions about the interactive way of the figure presented in the paper.

### ISSUE THREAD

**Issue by songbingze** [weihao1115/cat-sam#10]
Hi, I am very interested in your work. This is a very amazing method.

There are some issues with the MA. Roads in Fig. 4 of paper.
- Segment Anyting's result is that masks repeatedly predict by several click prompts from Mask Decoder, then concat. Or the mask is  directly predict by a group of clicks from Mask Decoder.
- I also have the same question about CAT-SAM.

Thank you very much for taking the time to review my question. Looking forward to your answer.

**Comment by weihao1115** [comment]
Hi @songbingze ,

Thank you for your interest in our work.

Regarding the two approaches you mentioned, we've focused on implementing the latter one. While we haven't tested the former approach ourselves, you're welcome to experiment with applying multiple click prompts sequentially to see if it works. We'd be interested to hear about your findings.
