### ISSUE TITLE
Request for the best_model.pth file used for reported results

### ISSUE THREAD

**Issue by sksmslhyr** [weihao1115/cat-sam#11]
Hi, Thank you for sharing your excellent work and for making this repository available to the community. I'm very interested in your work.

I have been working with your code and trying to reproduce the results reported in your paper. However, I am currently unable to achieve the same level of performance as mentioned in the paper. Specifically, the performance I obtained is about 4-5 lower than the results reported, despite following the provided instructions closely.

If it’s not too much trouble, would you be willing to share the specific best_model.pth file corresponding to the reported experimental results in the paper? Having access to this file would be incredibly helpful for verifying my setup and ensuring I’m not missing any key details.

Thank you very much for your time and consideration. I look forward to your response.

Best regards,

**Comment by weihao1115** [comment]
Hi @sksmslhyr ,

Thank you for your interest in our work.

Please check [here](https://github.com/weihao1115/cat-sam?tab=readme-ov-file#test).

**Comment by lava129** [comment]
Hello, can we only get better results by testing on a specific picture? The model I trained can never reach the results reported in your paper. If it is convenient, can you provide the weight file?
