### ISSUE TITLE
About the environment and dependencies

### ISSUE THREAD

**Issue by zzzyzh** [weihao1115/cat-sam#2]
Thank you for your outstanding work!

For some server reasons, it can be difficult to build an identical environment directly from yaml.

Could you please give us a list of torch versions and libraries we need to create a new environment directly?

**Comment by weihao1115** [comment]
Hi @zzzyzh 
Thank you for your interest in our work!

I have updated the installation procedure. Please check it. If you have any questions, please feel free to contact me.

**Comment by zzzyzh** [comment]
Another question is, does `cat_sam.models.segment_anything_vpt` mean `cat_sam.models.segment_anything_ext`? I can't find `cat_sam.models.segment_anything_vpt` in the repository.

**Comment by weihao1115** [comment]
I have updated the codebase yesterday. I guess you're using the last version of this repo, which is the test-only version.

Best regards,

**Comment by zzzyzh** [comment]
https://github.com/weihao1115/cat-sam/blob/659daadd404345ffca4e1603afe59df981c35f7e/cat_sam/models/modeling.py#L10

**Comment by weihao1115** [comment]
Sorry for the typo. I noticed there were some typos when we were reforming the code base to this public version. I have updated the code and tested several cases. Now, I guess it is bug-free.

Best regards,

**Comment by weihao1115** [comment]
I think the question has been resolved, so I close this issue here. Feel free to contact me again if you have any questions.

Best regards,
