### ISSUE TITLE
Make cat-SAM available on HF

### ISSUE THREAD

**Issue by NielsRogge** [weihao1115/cat-sam#5]
Hi,

Niels here from the open-source team at Hugging Face. As your paper is accepted as ECCV Oral (congrats!), I indexed the paper page: https://huggingface.co/papers/2402.03631 (feel free to claim the paper so that it appears under your HF account!). I work together with [AK](https://x.com/_akhaliq) on improving the visibility of researchers' work on the hub.

Was wondering if you're up for improving the discoverability of your work by making the models available on the hub rather than Google Drive, we can add tags so that people find them when filtering https://huggingface.co/models. 

For instance, the SAM models have the "mask-generation" tag: https://huggingface.co/models?pipeline_tag=mask-generation.

I'll add a guide below.

## Uploading models

In terms of uploading models, we provide a guide here: https://huggingface.co/docs/hub/models-uploading. In case the model is a custom PyTorch model, we could probably leverage the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds `from_pretrained` and `push_to_hub` to the model. Alternatively, one can leverage the [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file) one-liner to download a checkpoint from the hub. 

We encourage researchers to push each model checkpoint to a separate model repository, so that things like download stats also work. We can then also link the models to the paper page, as explained here: https://huggingface.co/docs/hub/en/model-cards#linking-a-paper

Let me know if you need any help regarding this! Happy to send a PR.

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by weihao1115** [comment]
Hi @NielsRogge ,

Nice to see you again! Thank you for your suggestion. We will update it in recent several days, just like our MM-SAM.

Best regards,
