### ISSUE TITLE
WHU dataset

### ISSUE THREAD

**Issue by XiaozhenQiao** [weihao1115/cat-sam#6]

**Comment by XiaozhenQiao** [comment]
Excellent work. I cannot download the WHU dataset. Is it because I need the WHU intranet to download it? Can you provide a way to publicly download the WHU dataset? Thank you.

**Comment by weihao1115** [comment]
Hi @XiaozhenQiao ,

Thank you for your interest in our work.

We found this [link](http://gpcv.whu.edu.cn/data/building_dataset.html) could be accessed, so please download the official dataset for the experiments.

Best regards,
