### ISSUE TITLE
Problem with cat-sam-a, 1-shot training results

### ISSUE THREAD

**Issue by WILSON10111** [weihao1115/cat-sam#9]
The training result（based on cat-sam-a, 1-shot，whu） for running on my own was 84，but the result mentioned in paper is 88.2?

**Comment by weihao1115** [comment]
Hi @WILSON10111 ,

Thank you for your interest in our work.

We have noticed the randomness according to this [issue](https://github.com/weihao1115/cat-sam/issues/8). We are thinking of incorporating some ways to reduce the randomness and improve the determinism of the code. Please also refer to the checkpoint for the results.

Best regards,
